# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-18 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('haveKit', models.CharField(choices=[('0', '\u5426'), ('1', '\u662f')], default='0', max_length=1)),
                ('kitId', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('paymentMethod', models.CharField(choices=[('wx', '\u5fae\u4fe1'), ('alipay', '\u652f\u4ed8\u5b9d')], default='wx', max_length=10)),
                ('radioInvoice', models.CharField(choices=[('1', '\u4e0d\u9700\u8981'), ('2', '\u4e2a\u4eba'), ('3', '\u516c\u53f8')], default='1', max_length=2)),
                ('invoice', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
