# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170318_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='kitId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
