# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170322_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='kitId',
            field=models.CharField(default='1111000000', max_length=12, unique=True),
        ),
    ]
