# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_productmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=30)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.orderModel')),
            ],
        ),
    ]
